// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"layout/google-console":{"path":"layout/google-console","id":"layout/google-console","file":"layout/google-console.tsx"}},
    routeComponents: {
'layout/google-console': React.lazy(() => import(/* webpackChunkName: "src__pages__layout__google-console" */'../../../src/pages/layout/google-console.tsx')),
},
  };
}
